currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:bOv9VzwtvbtNuPhxLT3oZ5Xat8qE8ufB}
server:
  port: 9090

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5431/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter
keycloak:
  auth-server-url: http://172.18.11.66:8081
  autodetect-bearer-only: true
  credentials:
    secret: 9nEENJr9g99XpUaze5ozJXBm59LofpX0
  realm: software
  ssl-required: none
  resource: backend
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
       - name: ADMINISTRADOR
         omitted-methods:
           - OPTIONS
         patterns:
          - /api/v1/diviapi/list
    - auth-roles:
        - USER
      security-collections:
        - name: USER
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/diviapi/convertion
