currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:bOv9VzwtvbtNuPhxLT3oZ5Xat8qE8ufB}
server:
  port: '{cipher}d67097c83cd5e279d7002fc6f0e278e0a992c5242094c67b08f182c046c6c4bd'

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:'{cipher}508c99ec574a0ab36aa5d8faf877bab458f2bf31e526780734ae94856e3f06be'
    password: ${PASSWORD:'{cipher}78c097136aca54e15167232e22f5e50316464c477b4150d57d2752a0f2b9fd5eec73cff71de42662afbabfe86512d25e'
    url: ${URL:jdbc:postgresql://localhost:5431/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter
keycloak:
  auth-server-url: http://172.18.11.66:8081
  autodetect-bearer-only: true
  credentials:
    secret: 9nEENJr9g99XpUaze5ozJXBm59LofpX0
  realm: software
  ssl-required: none
  resource: backend
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
       - name: ADMINISTRADOR
         omitted-methods:
           - OPTIONS
         patterns:
          - /api/v1/diviapi/list
    - auth-roles:
        - USER
      security-collections:
        - name: USER
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/diviapi/convertion
management:
  endpoints:
    web:
      exposure:
        include: "*"
